### ISSUE TITLE
about the experiments results

### ISSUE THREAD

**Issue by venuszhou** [yannadani/dlgm#1]
Hi, thanks for your reproducing. And I want to know have you test the code on the datasets in the paper? I mean I will be very appreciated if you could provide more information about this paper.

**Comment by yannadani** [comment]
Sorry for the misleading description. We are not reproducing the paper (which was the initial plan).

**Comment by venuszhou** [comment]
hey, I have noticed that the codes have been updated. I am curious when you test on the Sintel dataset, how the value of loss changes?
